# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qt81c5ZTsZYofbYgwz7X1p4ePBfSSkwa
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = pd.read_csv('/content/tested.csv')
data.head()
data.info()
data.describe()

print(data.isnull().sum())
data=data.fillna(data.mean())

x=data.drop(['Survived','Name',"Cabin","Sex","Embarked","Ticket"], axis=1)
y=data["Survived"]
x

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(x,y)

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")